### ISSUE TITLE
Code example with CUDA 12.3, Windows 11, Visual Studio 2022

### ISSUE THREAD

**Issue by exterity** [DoHITB/BigInteger.c#2]
Hi David,

Thank you for sharing this library.

I am trying to make the example code to work with CUDA 12.3 and Visual Studio Community 2022 version but there are many errors. I guess this problem is because I didn't config project properties properly.
May you please share the working example with Visual Studio Project file for reference?
Thank you.

**Comment by DoHITB** [comment]
Hi exterity!
Thanks for sharing your thoughts.

I replied the process step by step, and everyting runs fine.
Please, make sure to double check this particular things (because VStudio is sometimes a bit picky).

- Check that you created a CUDA project
- Check that you copied ```BigInteger.cu``` and ```BigInteger.h``` into the repo folder, also imported into the solution
- Check that you marked the ```-rdc=true``` option under ```CUDA C/C++ > Common``` 
- Check that you defined the preprocessor macros ```CUDA_ENABLED=1; BI_STANDALONE=1```  under ``` CUDA C/C++ > Host``` 

I will also be attaching a folder that I hope you can copy/paste so you don't have to play around with all the preferences everytime.
[Default Template.zip](https://github.com/DoHITB/BigInteger.c/files/14379098/Default.Template.zip)

When I have some time, I will update the main page to add a bit more of detail on how to make the first set-up.

Hope this solves your issue!

**Comment by exterity** [comment]
Just want to confirm with you that it also works with CUDA 12.3. Thank you.
